### ISSUE TITLE
Save world endpoint

### ISSUE THREAD

**Issue by matteoturini** [phybros/servertap#105]
Useful for backup automation

**Comment by phybros** [comment]
This will be pretty straightforward. Would be a good first issue for someone to work on

**Comment by phybros** [comment]
Wait, you can do this already!

You just do a POST request to `/v1/worlds/:uuid/save` with the UUID of the world OR send a POST to `/v1/worlds/save` which will save all worlds.

Let me know if you have any questions @matteoturini

**Comment by matteoturini** [comment]
Perfect! Thank you. Can the API also get the worlds as a compressed file?

**Comment by phybros** [comment]
No it can't. But you could make a new feature request for that if you like @matteoturini
