### ISSUE TITLE
Feature Request: Save & download world endpoint

### ISSUE THREAD

**Issue by matteoturini** [phybros/servertap#109]
An endpoint like `/v1/worlds/:uuid/download` or `/v1/worlds/download` to save & download worlds as a compressed file. Brotli would be preferred, but ZIP is good.

**Comment by phybros** [comment]
8x13b from discord is working on this https://discord.com/channels/919982507271802890/920026454207643688/920341302065905714

**Comment by matteoturini** [comment]
Closes with #110

**Comment by phybros** [comment]
Closed by #110
