### ISSUE TITLE
Come up with a plan for Error Handling

### ISSUE THREAD

**Issue by phybros** [phybros/servertap#11]
Right now, all errors are using status code `200 OK` and then including a raw string in the body.

Example:

```
HTTP/1.1 200 OK
Date: Thu, 30 Apr 2020 22:11:39 GMT
Server: Javalin
Content-Type: application/json
Content-Length: 42

"error: The server has whitelist disabled"
```

If you're writing a JSON client for this API there's nothing to tell you that there was an error. Usually you'd rely on the statusCode of the response. Some poorly implemented JSON parsers would also fail to parse just a string, even though it's technically correct JSON.

Some options:

1. Still just return a raw string, but include a relevant error code (`404 Not Found`, `405 Method Not Allowed` etc etc)
2. Keep returning 200 but create a JSON structure including some attribute like `"error": true`
3. Do nothing

@ATechAdventurer maybe you have opinions but I'm leaning towards 1.

**Comment by ATechAdventurer** [comment]
I'm good with option 1.

**Comment by phybros** [comment]
Well this is pretty neat. If you do `throw new InternalServerErrorResponse("error: The server has whitelist disabled");` instead of `ctx.json("error: The server has whitelist disabled");`

You get an HTTP `500 Internal Server Error` status code and a body of:

```
{
    "title": "error: The server has whitelist disabled",
    "status": 500,
    "type": "https://javalin.io/documentation#internalservererrorresponse",
    "details": []
}
```

**Comment by phybros** [comment]
@ATechAdventurer started using the pattern above, in combination with a centralized list of constant error codes on #9 so I'm going to close this and use that pattern going forward
