### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kial1** [phybros/servertap#12]
Hello,

First, I love your work with this plugin. Can I do sth. like /givemoney/80/<minecraft name>? Or can I perform any command (like /eco set <mc username> 80) with feedback?

~kial1

**Comment by ATechAdventurer** [comment]
Not at the moment. I am currently working on integrating Vault support but at this moment it is not a feature in the master branch. I am hoping I can finish this feature by the end of this week but no promises.

**Comment by kial1** [comment]
Do you think of any command support?

**Comment by ATechAdventurer** [comment]
I'm not entirely sure what you are asking but if I am correct you are asking about the ability to execute any command. While that is definitely a possibility for a feature it currently isn't and likely won't be as I feel like that is kinda out of the scope of the project, not to mention the security implications if any command can be executed from the endpoint it creates. Unless @phybros has a different vision. If you just need the ability to execute arbitrary commands and get the resulting feedback, you should look into using the built-in RCON protocol that is already installed in your server. Most languages have clients for interacting with the servers RCON.

**Comment by kial1** [comment]
Would be nice if you can finish the Vault support by the end of this week. Yeah executing commands is not really secure, you are right. Is there also a eta when there will be a auth support with a token or so?

~kial1

**Comment by ATechAdventurer** [comment]
I am not the creator of the project and don't know a ton about javalin in general. So that would be a question for @phybros.

**Comment by phybros** [comment]
I think an endpoint that allows you to run arbitrary commands might be an OK feature, but I would want to force the server admin to whitelist all commands that are allowed. I'm going to close this ticket since it's been answered.
