### ISSUE TITLE
Discord, Slack, Gitter or Rocketchat group

### ISSUE THREAD

**Issue by ATechAdventurer** [phybros/servertap#13]
@phybros It seems like there are quite a few people aware of this project, it would be cool to have a place you can funnel people if they want to ask questions or give feedback without spamming the Github issues. Is that something you would want to have? Given the nature of this project, I think a discord server would make sense but really any kind of group chat platform would work.

**Comment by phybros** [comment]
> quite a few people aware of this project

Got a source for that? I'd only want to invest time/effort if that's actually the case.

**Comment by phybros** [comment]
Made a Discord https://discord.gg/uS8VjEm @ATechAdventurer
