### ISSUE TITLE
Swagger UI not available when tls is enabled

### ISSUE THREAD

**Issue by he00741098** [phybros/servertap#138]
The swagger API is not available when I try to enable tls. Also getting console logs that javalin is outdated or something

**Comment by phybros** [comment]
It works for me @he00741098 

![image](https://user-images.githubusercontent.com/1985132/161072583-c8903b35-20ce-419e-8cf0-3df369918260.png)

Don't forget if you're using Chrome you will need to bypass the certificate error if your keystore is self-signed

**Comment by phybros** [comment]
closing due stale issue
