### ISSUE TITLE
In the player joining event it will cause a jam

### ISSUE THREAD

**Issue by shi-lai-mu** [phybros/servertap#155]
![76568b50c597aed71f33573ba84e9196](https://user-images.githubusercontent.com/45140991/172327829-b48961f6-445a-4b85-a827-403f8902a24f.png)

**Comment by telethonic** [comment]
Here's a "me too" post, except that I'm seeing it only for one (!) player when he logs in.

Attached the server log from the event, let me know if I can help with more info.
[servertap_delay.log](https://github.com/phybros/servertap/files/9336253/servertap_delay.log)

**Comment by shi-lai-mu** [comment]
I'm very sorry, I've given up on using it because the lag players can't stand it, so I can't provide more help

**Comment by telethonic** [comment]
Probably the issue should not be closed because someone stopped using the plugin?
