### ISSUE TITLE
Webhooks for server events

### ISSUE THREAD

**Issue by Earlh21** [phybros/servertap#37]
It would be nice to be able to register an IP to receive HTTP requests when certain events occur on the server, such as players leaving or joining.

**Comment by ATechAdventurer** [comment]
Yes, that was something I was planning on working on before things at work got really busy. If that is something you want to try and implement I say go for it, otherwise I could probably resume work on it in a couple of weeks.

**Comment by phybros** [comment]
Fixed in #38 !
