### ISSUE TITLE
Not all commands have output when using the execute endpoint.

### ISSUE THREAD

**Issue by TrevorBagels** [phybros/servertap#66]
For some reason, executing a command such as `help` will list all the commands in the response content, but something like 
`scoreboard players get theangrybagel totalKills` has no output in the response. (when I execute the command in the console, it shows output, but there isn't any output in the response)

**Comment by phybros** [comment]
From Discord:

> Isn’t possible for reasons I mentioned in the comments of my original PR
> It’s up to command handlers to properly send their output to the command sender, not all of them do
> There’s a message about that on the summary of the exec endpoint documentation
