### ISSUE TITLE
Webhook timings issue - Paper 1.17.1

### ISSUE THREAD

**Issue by c1oneman** [phybros/servertap#68]
Webhooks seem to be causing a massive performance impact on TPS. 
Provided below is the timings report from paper.
[https://timings.aikar.co/?id=8eb8bf944f3d4effab4f48782bbd96e3](https://timings.aikar.co/?id=8eb8bf944f3d4effab4f48782bbd96e3)

**Comment by phybros** [comment]
@c1oneman can you try this again with the latest version, and if possible can you capture

1. The timings info again
2. Your config.yml (don't include anything sensitive!)
3. Your server startup log

**Comment by phybros** [comment]
@c1oneman can you try this again with ServerTap v0.2.0, and provide the above info?

**Comment by phybros** [comment]
@c1oneman can you try this again with ServerTap v0.3.0, and provide the above info?

**Comment by LittleChest** [comment]
I have the same problem.
Spark: https://spark.lucko.me/fjH9O4vTfx

**Comment by LittleChest** [comment]
> Can you try again with v0.5.0 @LittleChest

did not solve the problem
![image](https://user-images.githubusercontent.com/81231195/233767200-333fcd4e-0b4a-4dfd-b8b4-6ff1daf16c67.png)

**Comment by MeesJ** [comment]
I can reproduce this, with the same data in the thread dump as @LittleChest's screenshot shows.
![](https://github.com/phybros/servertap/assets/77725857/f63960d6-61a7-484a-9ac0-9888a98fff33)

**Comment by phybros** [comment]
Yes I believe I fixed it in this commit: https://github.com/phybros/servertap/commit/88f45c691a3eb42e05287527bbd538e5d36113f2

The change prevents an additional lookup by hostname which can fail for IPv6 addresses.

I can make a release of 0.5.3 soon.

Some more details on Discord: https://discord.com/channels/919982507271802890/919982507271802893/1102610277276582019

**Comment by phybros** [comment]
@MeesJ Can you reliably repro it? If so maybe I'll send you a one off jar to test if that's ok

**Comment by MeesJ** [comment]
> @MeesJ Can you reliably repro it? If so maybe I'll send you a one off jar to test if that's ok

Yes, for specific users this issue always happens. So if you'd consider that as reliably reproducing it, feel free to send me the test jar. I'll be more than happy to test if it fixes the issue!

Bit off-topic, but wouldn't it be even better to offer hostname lookup as a setting in the config.yml? For people who just want people's raw IP addresses instead of the rDNS value of their IP addresses, it'd be more efficient to be able to disable this mechanism entirely.

**Comment by phybros** [comment]
Cool. I would bet those specific users are using IPv6!

I'll see if I can send a build shortly

**Comment by MeesJ** [comment]
> Cool. I would bet those specific users are using IPv6!

That doesn't seem to be the case. since they're playing via IPv4 from what it looks like. I'm playing via IPv6 myself and I do not cause any lookup issues.

**Comment by LittleChest** [comment]
> Cool. I would bet those specific users are using IPv6!
> 
> I'll see if I can send a build shortly

No, I even disabled IPv6 in the network settings to prevent the server from getting IPv6.
Feel free to send a beta version if you like. ฅ⁠^⁠•⁠ﻌ⁠•⁠^⁠ฅ

**Comment by MeesJ** [comment]
It looks like the snapshot has fixed the issue for me. I also like it that you changed the address field to no longer trigger a rDNS lookup!

Is it okay for you that I keep this snapshot for now? It's running smoothly for both IPv4 and IPv6 users.

**Comment by phybros** [comment]
Yeah for sure. I'll do a proper release of 0.5.3 very soon too.

**Comment by phybros** [comment]
v0.5.3 was just released. Enjoy!
