### ISSUE TITLE
Add ability to get more detailed user info

### ISSUE THREAD

**Issue by shawnco** [phybros/servertap#70]
From a server management side, it would be useful if I could see more detailed things about my players. For instance what dimension they're in, what their coordinates are, etc. 

Right now I think I could approximate this with the v1/server/exec endpoint, having it do /data get entity Username. This returns a lot of info about the user. However having this data returned by the v1/player route (and perhaps even updatable through POST/PUT) would be much nicer!

**Comment by koutsie** [comment]
IMO, https://github.com/phybros/servertap/issues/74 could mesh and add to this really well, considering PAPI has a lot of player related placeholders:
- [Player](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player)
- [PlayerList](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#player)
- [OtherPlayer](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#otherplayer)
and maybe even:
- [World](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#world)
- [MultiverseCore](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#multiverse-core) (From the Multiverse plugin)

**Comment by phybros** [comment]
Closed in #106
