### ISSUE TITLE
Feature request: PlaceholderAPI?

### ISSUE THREAD

**Issue by koutsie** [phybros/servertap#74]
Having PlaceholderAPI support would open so many possibilities for servertap to become even more useful in my humble opinion.
- PlaceholderAPI: https://github.com/PlaceholderAPI/PlaceholderAPI

**Comment by phybros** [comment]
@koutsie can you talk any more about how you see this working in an ideal world? Would there be new API routes for ServerTap? If so what would they be?

Do you just want to be able to get the placeholder configs? Or actually a rendered out thing

**Comment by koutsie** [comment]
Yeah nothing too complicated, just get PAPI values.
