### ISSUE TITLE
Feature request: Selective auth?

### ISSUE THREAD

**Issue by koutsie** [phybros/servertap#75]
Eg: I'd like the auth key be asked for everything else but for example getting a scoreboard.
This'd make fetching stuff client side (eg a website with js) possible "securely" (not exposing ex: add ops to the client (because they don't need the key to get what they need))

**Comment by c1oneman** [comment]
One solution is to build a middleware API for your own system to handle auth and routes.

**Comment by koutsie** [comment]
> One solution is to build a middleware API for your own system to handle auth and routes.

Yeah is, but i guess what i'm trying to say is to have an "publicly accesible" server api so that people can fetch public data permissively.

**Comment by phybros** [comment]
@c1oneman you actually already implemented this but didn't know it.

Just have to change this line to be the swagger paths PLUS a list from the config file :) https://github.com/phybros/servertap/blob/master/src/main/java/io/servertap/PluginEntrypoint.java#L68

**Comment by phybros** [comment]
Closing this in favor of #6 I will ensure this is possible in the new auth system
