### ISSUE TITLE
Load latest server log on console ws connection. 

### ISSUE THREAD

**Issue by srmullaney** [phybros/servertap#96]
Could we add the ability to send the latest server log to the client on a web socket connection? 

It should basically be this https://bitbucket.org/phybros/swiftapi/src/41595c76fc2f97d93da188c8dcafd404cd82d60b/src/main/java/org/phybros/minecraft/SwiftFilter.java#lines-48:61

**Comment by phybros** [comment]
So you're saying that you would open the connection and it would immediately send the last 1000 log lines through the newly opened connection @srmullaney?

Can also make the 1000 configurable in the config file (default to 1000).

**Comment by srmullaney** [comment]
@phybros Yes.

I love the idea to make it configurable.

**Comment by phybros** [comment]
Cool. Almost finished!

**Comment by srmullaney** [comment]
Cool! Will the lines sent have all the color codes etc?

**Comment by phybros** [comment]
Yes

**Comment by srmullaney** [comment]
Okay, cool.
